// Auto-generated. Maps Arabic UI strings -> {fr, en} for ops pages.
import i18n from "./i18n";

const dict: Record<string, { fr: string; en: string }> = {
  "الاسم": { fr: "Nom", en: "Name" },
  "حفظ": { fr: "Enregistrer", en: "Save" },
  "جاري الحفظ…": { fr: "Enregistrement...", en: "Saving..." },
  "إلغاء": { fr: "Annuler", en: "Cancel" },
  "ملاحظات": { fr: "Notes", en: "Notes" },
  "الهاتف": { fr: "Téléphone", en: "Phone" },
  "مشتريات الموردين": { fr: "Achats Fournisseurs", en: "Supplier purchases" },
  "الوحدة": { fr: "Unité", en: "Unit" },
  "السبب": { fr: "Raison", en: "Reason" },
  "فشل التعديل": { fr: "Échec de la modification", en: "Modification failed" },
  "جاري الحفظ...": { fr: "Enregistrement...", en: "Saving..." },
  "الدور": { fr: "Rôle", en: "Role" },
  "إجمالي الإيرادات": { fr: "Revenus totaux", en: "Total Revenue" },
  "مصاريف التشغيل": { fr: "Dépenses d'exploitation", en: "Operating Expenses" },
  "جديدة": { fr: "Nouveau", en: "New" },
  "قيد المعالجة": { fr: "En cours de traitement", en: "In Progress" },
  "تم الحل": { fr: "Résolu", en: "Resolved" },
  "شهري": { fr: "Mensuel", en: "Monthly" },
  "يومي": { fr: "Quotidien", en: "Daily" },
  "بالساعة": { fr: "Horaire", en: "Hourly" },
  "تم التعديل": { fr: "Modifié", en: "Modified" },
  "تم الحذف": { fr: "Supprimé", en: "Deleted" },
  "نوع الراتب": { fr: "Type de salaire", en: "Salary Type" },
  "تعديل": { fr: "Modifier", en: "Edit" },
  "حذف": { fr: "Supprimer", en: "Delete" },
  "الشهر": { fr: "Mois", en: "Month" },
  "مصاريف أخرى": { fr: "Autres dépenses", en: "Other expenses" },
  "فشل الحفظ": { fr: "Échec de l'enregistrement", en: "Save failed" },
  "رواتب العمال": { fr: "Salaires des travailleurs", en: "Workers' salaries" },
  "التاريخ": { fr: "Date", en: "Date" },
  "جاري التحميل…": { fr: "Chargement en cours…", en: "Loading…" },
  "آخر 7 أيام": { fr: "7 derniers jours", en: "Last 7 days" },
  "الدين السابق": { fr: "Dette précédente", en: "Previous debt" },
  "الكمية": { fr: "Quantité", en: "Quantity" },
  "تكلفة الهدر": { fr: "Coût des déchets", en: "Waste cost" },
  "لا توجد بيانات": { fr: "Pas de données", en: "No data" },
  "تم التحديث": { fr: "Mis à jour", en: "Updated" },
  "الكل": { fr: "Tout", en: "All" },
  "الحالة": { fr: "Statut", en: "Status" },
  "الاسم مطلوب": { fr: "Nom requis", en: "Name required" },
  "تمت الإضافة": { fr: "Ajouté", en: "Added" },
  "عميل جديد": { fr: "Nouveau client", en: "New client" },
  "الاسم والدور مطلوبان": { fr: "Nom et rôle requis", en: "Name and role required" },
  "الموظفين": { fr: "Employés", en: "Employees" },
  "المبلغ": { fr: "Montant", en: "Amount" },
  "المبلغ (دج)": { fr: "Montant (DA)", en: "Amount (DA)" },
  "الربح الصافي": { fr: "Bénéfice net", en: "Net profit" },
  "الخسارة الصافية": { fr: "Perte nette", en: "Net loss" },
  "نسخ المتكرر": { fr: "Copie dupliquée", en: "Duplicate copy" },
  "الإيرادات": { fr: "Revenus", en: "Revenue" },
  "الفئة": { fr: "Catégorie", en: "Category" },
  "صافي الربح": { fr: "Bénéfice net", en: "Net profit" },
  "مُقفل": { fr: "Verrouillé", en: "Locked" },
  "مفتوح": { fr: "Ouvert", en: "Open" },
  "المكوّن": { fr: "Ingrédient", en: "Ingredient" },
  "جرد المخزون": { fr: "Inventaire", en: "Inventory" },
  "محروق": { fr: "Brûlé", en: "Burned" },
  "منتهي الصلاحية": { fr: "Expiré", en: "Expired" },
  "سقط/تلف": { fr: "Tombé/Endommagé", en: "Dropped/Damaged" },
  "خطأ في التحضير": { fr: "Erreur de préparation", en: "Preparation error" },
  "أخرى": { fr: "Autre", en: "Other" },
  "تم إرسال تنبيه Telegram للمخزون الناقص": { fr: "Alerte Telegram pour stock faible envoyée", en: "Telegram alert for low stock sent" },
  "الاسم والوحدة مطلوبان": { fr: "Nom et unité sont obligatoires", en: "Name and unit are required" },
  "فشل إضافة المورد": { fr: "Échec de l'ajout du fournisseur", en: "Failed to add supplier" },
  "فشل تسجيل الهدر": { fr: "Échec de l'enregistrement du gaspillage", en: "Failed to log waste" },
  "تسجيل": { fr: "Enregistrer", en: "Log" },
  "إضافة للمخزون": { fr: "Ajouter au stock", en: "Add to stock" },
  "خصم من المخزون": { fr: "Déduire du stock", en: "Deduct from stock" },
  "الكمية الحالية": { fr: "Quantité actuelle", en: "Current quantity" },
  "السعر/وحدة": { fr: "Prix/unité", en: "Price/unit" },
  "حد التنبيه": { fr: "Seuil d'alerte", en: "Alert threshold" },
  "السعر/وحدة (دج)": { fr: "Prix/unité (DA)", en: "Price/unit (DA)" },
  "سجّله (اسم الطباخ)": { fr: "Enregistré par (nom du cuisinier)", en: "Logged by (cook's name)" },
  "المجموع": { fr: "Total", en: "Total" },
  "هذا الشهر": { fr: "Ce mois-ci", en: "This month" },
  "هذا الربع": { fr: "Ce trimestre", en: "This Quarter" },
  "هذه السنة": { fr: "Cette année", en: "This Year" },
  "المصاريف": { fr: "Dépenses", en: "Expenses" },
  "رواتب الموظفين": { fr: "Salaires des employés", en: "Employee Salaries" },
  "اختر المورد": { fr: "Sélectionnez le fournisseur", en: "Select Supplier" },
  "إضافة مورد": { fr: "Ajouter un fournisseur", en: "Add Supplier" },
  "فاتورة شراء جديدة": { fr: "Nouvelle facture d'achat", en: "New Purchase Invoice" },
  "سجل الهدر": { fr: "Journal des déchets", en: "Waste Log" },
  "اذكر السبب": { fr: "Spécifiez la raison", en: "Specify Reason" },
  "تسجيل هدر": { fr: "Enregistrer le gaspillage", en: "Register Waste" },
  "المكون": { fr: "Ingrédient", en: "Ingredient" },
  "مجهول": { fr: "Inconnu", en: "Unknown" },
  "لا توجد شكاوى": { fr: "Aucune réclamation", en: "No Complaints" },
  "تفاصيل الشكوى": { fr: "Détails de la réclamation", en: "Complaint Details" },
  "النوع:": { fr: "Type:", en: "Type:" },
  "الوصف:": { fr: "Description:", en: "Description:" },
  "العميل:": { fr: "Client:", en: "Customer:" },
  "ملاحظات الحل": { fr: "Notes de résolution", en: "Resolution Notes" },
  "أدخل قيمة صحيحة": { fr: "Veuillez entrer une valeur valide", en: "Enter a valid value" },
  "تم تحديث النقاط": { fr: "Points mis à jour", en: "Points Updated" },
  "بحث بالاسم أو الهاتف": { fr: "Rechercher par nom ou téléphone", en: "Search by Name or Phone" },
  "تعديل عميل": { fr: "Modifier le client", en: "Edit Customer" },
  "مثلاً: استبدال هدية": { fr: "Ex: Échange de cadeau", en: "Ex: Gift replacement" },
  "نقاط": { fr: "Points", en: "Points" },
  "لا يوجد عملاء": { fr: "Pas de clients", en: "No Customers" },
  "عدد النقاط (سالب لخصم/استبدال)": { fr: "Nombre de points (négatif pour réduction/échange)", en: "Number of points (negative for discount/redemption)" },
  "تطبيق": { fr: "Appliquer", en: "Apply" },
  "فشل تحميل الموظفين": { fr: "Échec du chargement des employés", en: "Failed to load employees" },
  "فشل إضافة الموظف": { fr: "Échec de l'ajout de l'employé", en: "Failed to add employee" },
  "المبلغ غير صحيح": { fr: "Montant incorrect", en: "Incorrect amount" },
  "فشل تسجيل الدفع": { fr: "Échec de l'enregistrement du paiement", en: "Failed to record payment" },
  "تم تسجيل الدفع": { fr: "Paiement enregistré", en: "Payment recorded" },
  "فشل التحديث": { fr: "Échec de la mise à jour", en: "Update failed" },
  "حذف \"${e.name}\"؟ سجل الرواتب سيُحذف معه.": { fr: "Supprimer \"${e.name}\" ? Le registre des salaires sera également supprimé.", en: "Delete \"${e.name}\"? Payroll records will be deleted with it." },
  "فشل الحذف — قد يكون مرتبطاً بمدفوعات": { fr: "Échec de la suppression — peut être lié à des paiements", en: "Deletion failed — may be linked to payments" },
  "دج/شهر": { fr: "DA/mois", en: "DA/month" },
  "دج/يوم": { fr: "DA/jour", en: "DA/day" },
  "دج/ساعة": { fr: "DA/heure", en: "DA/hour" },
  "إيقاف": { fr: "Désactiver", en: "Deactivate" },
  "تفعيل": { fr: "Activer", en: "Activate" },
  "الراتب الشهري (دج)": { fr: "Salaire mensuel (DA)", en: "Monthly salary (DA)" },
  "السعر/اليوم (دج)": { fr: "Prix/jour (DA)", en: "Price/day (DA)" },
  "السعر/الساعة (دج)": { fr: "Prix/heure (DA)", en: "Price/hour (DA)" },
  "عدد الأيام": { fr: "Nombre de jours", en: "Number of days" },
  "عدد الساعات": { fr: "Nombre d'heures", en: "Number of hours" },
  "تسجيل الدفع": { fr: "Enregistrer le paiement", en: "Record payment" },
  "الموظفين النشطين": { fr: "Employés actifs", en: "Active employees" },
  "مدفوع هذا الشهر": { fr: "Payé ce mois-ci", en: "Paid this month" },
  "إضافة موظف": { fr: "Ajouter un employé", en: "Add employee" },
  "الأساس": { fr: "Base", en: "Base" },
  "حالة هذا الشهر": { fr: "Statut de ce mois", en: "This month's status" },
  "إجراءات": { fr: "Actions", en: "Actions" },
  "غير نشط": { fr: "Inactif", en: "Inactive" },
  "معلّق": { fr: "En attente", en: "Pending" },
  "دفع راتب": { fr: "Payer le salaire", en: "Pay salary" },
  "اقتطاعات وراتب": { fr: "Déductions et salaire", en: "Deductions and salary" },
  "آخر المدفوعات": { fr: "Derniers paiements", en: "Last payments" },
  "الموظف": { fr: "Employé", en: "Employee" },
  "الوحدات": { fr: "Unités", en: "Units" },
  "تاريخ الدفع": { fr: "Date de paiement", en: "Payment date" },
  "إضافة موظف جديد": { fr: "Ajouter un nouvel employé", en: "Add new employee" },
  "الدور (طباخ، نادل، ...)": { fr: "Rôle (cuisinier, serveur, ...)", en: "Role (cook, waiter, ...)" },
  "تعديل الموظف": { fr: "Modifier l'employé", en: "Edit employee" },
  "الأساس (دج)": { fr: "Base (DA)", en: "Base (DA)" },
  "الإيجار": { fr: "Loyer", en: "Rent" },
  "الكهرباء والماء": { fr: "Électricité et eau", en: "Electricity and water" },
  "الإنترنت": { fr: "Internet", en: "Internet" },
  "تأمينات العمال": { fr: "Assurances des travailleurs", en: "Workers' insurance" },
  "الصيانة والإصلاحات": { fr: "Maintenance et réparations", en: "Maintenance and repairs" },
  "نقل العمال والبضائع": { fr: "Transport des travailleurs et des marchandises", en: "Transport of workers and goods" },
  "أدخل مبلغاً صحيحاً": { fr: "Entrez un montant valide", en: "Enter a valid amount" },
  "تمت إضافة المصروف": { fr: "Dépense ajoutée", en: "Expense added" },
  "حذف هذا المصروف؟": { fr: "Supprimer cette dépense ?", en: "Delete this expense?" },
  "فشل الحذف": { fr: "Échec de la suppression", en: "Deletion failed" },
  "لا توجد مصاريف متكررة من الشهر الماضي": { fr: "Aucune dépense récurrente du mois dernier", en: "No recurring expenses from last month" },
  "كل المصاريف المتكررة موجودة": { fr: "Toutes les dépenses récurrentes sont présentes", en: "All recurring expenses are present" },
  "فشل النسخ": { fr: "Échec de la copie", en: "Copy failed" },
  "تم نسخ ${toInsert.length} مصروف": { fr: "${toInsert.length} dépense copiée", en: "${toInsert.length} expense copied" },
  "<!doctype html><html dir=\"rtl\" lang=\"ar\"><head><meta charset=\"utf-8\"/>\n      <title>تقرير الربح — ${month}</title>\n      <style>\n        body{font-family:Cairo,system-ui,sans-serif;padding:24px;color:#111}\n        h1{margin:0 0 12px}\n        table{width:100%;border-collapse:collapse;font-size:14px}\n        td{padding:8px 10px;border-bottom:1px solid #eee}\n        .total{font-weight:bold;font-size:18px;background:#fafafa}\n        .pos{color:#16a34a} .neg{color:#dc2626}\n      </style></head><body>\n      <h1>تقرير الربح الحقيقي — ${month}</h1>\n      <table>\n        <tr><td>إجمالي الإيرادات</td><td style=\"text-align:left\" class=\"pos\">+ ${formatDZD(revenue)}</td></tr>\n        <tr><td>مصاريف التشغيل</td><td style=\"text-align:left\" class=\"neg\">- ${formatDZD(totalThisMonth)}</td></tr>\n        <tr><td>مشتريات الموردين</td><td style=\"text-align:left\" class=\"neg\">- ${formatDZD(supplierPurchases)}</td></tr>\n        <tr><td>رواتب العمال</td><td style=\"text-align:left\" class=\"neg\">- ${formatDZD(employeeSalaries)}</td></tr>\n        <tr class=\"total\"><td>${profit >= 0 ? \"الربح الصافي\" : \"الخسارة الصافية\"}</td>\n          <td style=\"text-align:left\" class=\"${profit >= 0 ? \"pos\" : \"neg\"}\">${formatDZD(profit)}</td></tr>\n      </table>\n      <script>window.onload=()=>setTimeout(()=>window.print(),300)</script>\n      </body></html>": { fr: "<!doctype html><html dir=\"rtl\" lang=\"ar\"><head><meta charset=\"utf-8\"/><title>Rapport de profit — ${month}</title><style>body{font-family:Cairo,system-ui,sans-serif;padding:24px;color:#111}h1{margin:0 0 12px}table{width:100%;border-collapse:collapse;font-size:14px}td{padding:8px 10px;border-bottom:1px solid #eee}.total{font-weight:bold;font-size:18px;background:#fafafa}.pos{color:#16a34a}.neg{color:#dc2626}</style></head><body><h1>Rapport de profit réel — ${month}</h1><table><tr><td>Revenu total</td><td style=\"text-align:left\" class=\"pos\">+ ${formatDZD(revenue)}</td></tr><tr><td>Frais d'exploitation</td><td style=\"text-align:left\" class=\"neg\">- ${formatDZD(totalThisMonth)}</td></tr><tr><td>Achats fournisseurs</td><td style=\"text-align:left\" class=\"neg\">- ${formatDZD(supplierPurchases)}</td></tr><tr><td>Salaires des employés</td><td style=\"text-align:left\" class=\"neg\">- ${formatDZD(employeeSalaries)}</td></tr><tr class=\"total\"><td>${profit >= 0 ? \"Bénéfice net\" : \"Perte nette\"}</td><td style=\"text-align:left\" class=\"${profit >= 0 ? \"pos\" : \"neg\"}\">${formatDZD(profit)}</td></tr></table><script>window.onload=()=>setTimeout(()=>window.print(),300)</script></body></html>", en: "<!doctype html><html dir=\"rtl\" lang=\"ar\"><head><meta charset=\"utf-8\"/><title>Profit report — ${month}</title><style>body{font-family:Cairo,system-ui,sans-serif;padding:24px;color:#111}h1{margin:0 0 12px}table{width:100%;border-collapse:collapse;font-size:14px}td{padding:8px 10px;border-bottom:1px solid #eee}.total{font-weight:bold;font-size:18px;background:#fafafa}.pos{color:#16a34a}.neg{color:#dc2626}</style></head><body><h1>Real Profit Report — ${month}</h1><table><tr><td>Total Revenue</td><td style=\"text-align:left\" class=\"pos\">+ ${formatDZD(revenue)}</td></tr><tr><td>Operating Expenses</td><td style=\"text-align:left\" class=\"neg\">- ${formatDZD(totalThisMonth)}</td></tr><tr><td>Supplier Purchases</td><td style=\"text-align:left\" class=\"neg\">- ${formatDZD(supplierPurchases)}</td></tr><tr><td>Employee Salaries</td><td style=\"text-align:left\" class=\"neg\">- ${formatDZD(employeeSalaries)}</td></tr><tr class=\"total\"><td>${profit >= 0 ? \"Net Profit\" : \"Net Loss\"}</td><td style=\"text-align:left\" class=\"${profit >= 0 ? \"pos\" : \"neg\"}\">${formatDZD(profit)}</td></tr></table><script>window.onload=()=>setTimeout(()=>window.print(),300)</script></body></html>" },
  "نعم": { fr: "Oui", en: "Yes" },
  "مصروف جديد": { fr: "Nouvelle dépense", en: "New expense" },
  "إجمالي مصاريف الشهر": { fr: "Total des dépenses du mois", en: "Total expenses for the month" },
  "تقرير الربح الحقيقي": { fr: "Rapport de profit réel", en: "Real profit report" },
  "تصدير PDF": { fr: "Exporter en PDF", en: "Export PDF" },
  "حسب الفئة": { fr: "Par catégorie", en: "By category" },
  "لا بيانات": { fr: "Pas de données", en: "No data" },
  "آخر 3 أشهر": { fr: "Derniers 3 mois", en: "Last 3 months" },
  "متكرر": { fr: "Récurrent", en: "Recurring" },
  "لا مصاريف لهذا الشهر": { fr: "Pas de dépenses pour ce mois", en: "No expenses for this month" },
  "إضافة مصروف": { fr: "Ajouter une dépense", en: "Add expense" },
  "الوصف": { fr: "Description", en: "Description" },
  "شهري متكرر": { fr: "Récurrent mensuel", en: "Monthly recurring" },
  "يظهر في زر \"نسخ المتكرر\"": { fr: "Apparaît dans le bouton \"Copier récurrent\"", en: "Appears in \"Copy Recurring\" button" },
  "إيرادات هذا الشهر": { fr: "Revenus de ce mois", en: "Revenue this month" },
  "${fmt(kpis.monthRevenue)} دج": { fr: "${fmt(kpis.monthRevenue)} DA", en: "${fmt(kpis.monthRevenue)} DA" },
  "طلبات مدفوعة": { fr: "Commandes payées", en: "Paid orders" },
  "${fmt(kpis.monthNet)} دج": { fr: "${fmt(kpis.monthNet)} DA", en: "${fmt(kpis.monthNet)} DA" },
  "إيرادات − (مشتريات + رواتب + هدر)": { fr: "Revenus − (Achats + Salaires + Déchets)", en: "Revenue − (Purchases + Salaries + Waste)" },
  "مصاريف هذا الشهر": { fr: "Dépenses de ce mois", en: "Expenses this month" },
  "${fmt(kpis.monthExpenses)} دج": { fr: "${fmt(kpis.monthExpenses)} DA", en: "${fmt(kpis.monthExpenses)} DA" },
  "مشتريات + رواتب": { fr: "Achats + Salaires", en: "Purchases + Salaries" },
  "مكونات ناقصة": { fr: "Ingrédients manquants", en: "Missing ingredients" },
  "أقل من حد التنبيه": { fr: "Moins que le seuil d'alerte", en: "Less than alert threshold" },
  "رواتب معلقة": { fr: "Salaires en attente", en: "Pending salaries" },
  "موظفين لم يُدفعوا هذا الشهر": { fr: "Employés impayés ce mois-ci", en: "Employees unpaid this month" },
  "تكلفة الهدر هذا الأسبوع": { fr: "Coût du gaspillage cette semaine", en: "Waste cost this week" },
  "${fmt(kpis.weekWaste)} دج": { fr: "${fmt(kpis.weekWaste)} DA", en: "${fmt(kpis.weekWaste)}Algerian Dinar" },
  "خطأ": { fr: "Erreur", en: "Error" },
  "تم بدء جرد جديد": { fr: "Un nouvel inventaire a été démarré", en: "A new inventory has been started" },
  "تم إقفال الجرد": { fr: "L'inventaire a été clôturé", en: "The inventory has been closed" },
  "طباعة": { fr: "Imprimer", en: "Print" },
  "إقفال": { fr: "Fermer", en: "Close" },
  "عودة": { fr: "Retour", en: "Back" },
  "جار التحميل...": { fr: "Chargement...", en: "Loading..." },
  "المتوقع": { fr: "Prévu", en: "Expected" },
  "المعدود": { fr: "Compté", en: "Counted" },
  "الفرق": { fr: "Différence", en: "Difference" },
  "قيمة الفرق": { fr: "Valeur de la différence", en: "Difference value" },
  "قارن المخزون الفعلي بالمخزون النظري واستخرج الفروقات.": { fr: "Comparez l'inventaire physique avec l'inventaire théorique et identifiez les différences.", en: "Compare physical inventory with theoretical inventory and identify differences." },
  "جرد جديد": { fr: "Nouvel inventaire", en: "New inventory" },
  "لا توجد عمليات جرد": { fr: "Aucune opération d'inventaire", en: "No inventory operations" },
  "فشل تحميل المكونات": { fr: "Échec du chargement des composants", en: "Failed to load components" },
  "فشل إضافة المكون: ${error.message}": { fr: "Échec de l'ajout du composant : ${error.message}", en: "Failed to add component: ${error.message}" },
  "تمت إضافة المكون": { fr: "Composant ajouté", en: "Component added" },
  "لم نستطع قراءة أي عنصر — جرّب صورة أوضح": { fr: "Nous n'avons pas pu lire d'éléments — essayez une image plus claire", en: "We couldn’t read any items — try a clearer image" },
  "تم استخراج ${r.items.length} عنصر": { fr: "{{r.items.length}} article(s) extrait(s)", en: "{{r.items.length}} item(s) extracted" },
  "فشل تحليل الصورة": { fr: "Échec de l'analyse de l'image", en: "Failed to parse image" },
  "لا توجد عناصر للحفظ": { fr: "Aucun article à enregistrer", en: "No items to save" },
  "اسم المورد مطلوب لحفظ الفاتورة في حساب المورد": { fr: "Le nom du fournisseur est requis pour enregistrer la facture sur le compte du fournisseur", en: "Vendor name is required to save invoice to vendor's account" },
  "حبة": { fr: "Pièce", en: "Piece" },
  "فشل إضافة المكون": { fr: "Échec de l'ajout de l'ingrédient", en: "Failed to add ingredient" },
  "فاتورة مصورة${previousDebt ? ": { fr: "Facture image${previousDebt ? ", en: "Image invoice${previousDebt ? " },
  "فشل إنشاء فاتورة المورد": { fr: "Échec de la création de la facture fournisseur", en: "Failed to create vendor invoice" },
  "فاتورة مصورة #${po.id.slice(0, 8)}": { fr: "Facture image #${po.id.slice(0, 8)}", en: "Image invoice #${po.id.slice(0, 8)}" },
  "المبلغ المدفوع من الفاتورة المصورة": { fr: "Montant payé de la facture image", en: "Amount paid from image invoice" },
  "الدين السابق المستخرج من الفاتورة": { fr: "Dette précédente extraite de la facture", en: "Previous debt extracted from invoice" },
  "تمت إضافة ${processed} مكون للمخزون": { fr: "{{processed}} ingrédient(s) ajouté(s) au stock", en: "{{processed}} ingredients added to inventory" },
  "فشل حفظ الفاتورة": { fr: "Échec de l'enregistrement de la facture", en: "Failed to save invoice" },
  "أدخل الكمية": { fr: "Entrez la quantité", en: "Enter quantity" },
  "سُجِّل الهدر لكن فشل تحديث المخزون": { fr: "Déchet enregistré mais échec de la mise à jour de l'inventaire", en: "Waste logged but inventory update failed" },
  "تم تسجيل الهدر": { fr: "Déchet enregistré", en: "Waste logged" },
  "حذف \"${ing.name}\"؟ لا يمكن التراجع.": { fr: "Supprimer \"{{ing.name}}\" ? Cette action est irréversible.", en: "Delete \"{{ing.name}}\"? Cannot be undone." },
  "فشل الحذف — قد يكون مرتبطاً بسجلات": { fr: "Échec de la suppression — peut être lié à des enregistrements", en: "Deletion failed — may be linked to records" },
  "أدخل كمية صحيحة": { fr: "Entrez une quantité valide", en: "Enter a valid quantity" },
  "تمت الإضافة للمخزون": { fr: "Ajouté au stock", en: "Added to inventory" },
  "تم الخصم من المخزون": { fr: "Déduit du stock", en: "Deducted from inventory" },
  "مثال: طماطم": { fr: "Exemple : tomates", en: "Example: tomatoes" },
  "كغ / لتر / حبة": { fr: "Kg / Litre / Pièce", en: "Kg / Liter / Piece" },
  "إضافة/خصم من المخزون": { fr: "Ajouter/Retirer du stock", en: "Add/Deduct from inventory" },
  "مثال: شراء سريع، تصحيح جرد...": { fr: "Exemple : achat rapide, correction d'inventaire...", en: "Example: quick purchase, inventory correction..." },
  "تأكيد": { fr: "Confirmer", en: "Confirm" },
  "مثال: جاري للتجارة": { fr: "Exemple : Jari Trading", en: "Example: Jari Trading" },
  "حفظ (${recItems.length})": { fr: "Enregistrer (${recItems.length})", en: "Save (${recItems.length})" },
  "تصوير الفاتورة": { fr: "Facture photo", en: "Photograph invoice" },
  "إضافة مكون": { fr: "Ajouter un ingrédient", en: "Add ingredient" },
  "الحد": { fr: "Limite", en: "Limit" },
  "إجراء": { fr: "Action", en: "Action" },
  "ناقص": { fr: "Moins", en: "Minus" },
  "جيد": { fr: "Bon", en: "Good" },
  "هدر": { fr: "Gaspillage", en: "Waste" },
  "إضافة مكون جديد": { fr: "Ajouter un nouvel ingrédient", en: "Add new ingredient" },
  "وصف السبب": { fr: "Décrire la raison", en: "Describe reason" },
  "تعديل المكون": { fr: "Modifier l'ingrédient", en: "Edit ingredient" },
  "ملاحظة (اختياري)": { fr: "Remarque (facultatif)", en: "Note (optional)" },
  "تصوير فاتورة شراء": { fr: "Photographier la facture d'achat", en: "Photograph purchase invoice" },
  "اضغط لالتقاط صورة أو رفع ملف": { fr: "Cliquez pour prendre une photo ou télécharger un fichier", en: "Click to take a photo or upload a file" },
  "جاري تحليل الصورة…": { fr: "Analyse de l'image…", en: "Analyzing image…" },
  "اسم المورد": { fr: "Nom du fournisseur", en: "Supplier name" },
  "الدين الإجمالي": { fr: "Dette totale", en: "Total debt" },
  "المبلغ المدفوع": { fr: "Montant payé", en: "Amount paid" },
  "تم حفظ الوصفة": { fr: "Recette enregistrée", en: "Recipe saved" },
  "بحث صنف...": { fr: "Rechercher une catégorie...", en: "Search category..." },
  "بدون وصفة": { fr: "Sans recette", en: "Without recipe" },
  "${rs.length} مكوّن": { fr: "${rs.length} ingrédient", en: "${rs.length} ingredient" },
  "اختر...": { fr: "Sélectionnez...", en: "Select..." },
  "تكلفة": { fr: "Coût", en: "Cost" },
  "ربح": { fr: "Bénéfice", en: "Profit" },
  "إضافة مكوّن": { fr: "Ajouter un ingrédient", en: "Add ingredient" },
  "القسم,البند,القيمة": { fr: "Section,Article,Valeur", en: "Section,Item,Value" },
  "الفترة,${labelOf[range]},": { fr: "Période,${labelOf[range]},", en: "Period,${labelOf[range]}," },
  "ملخص,الإيرادات (طلبات مدفوعة),${data.revenue}": { fr: "Résumé,Revenus (commandes payées),${data.revenue}", en: "Summary,Revenue (paid orders),${data.revenue}" },
  "ملخص,المشتريات,${data.purchases}": { fr: "Résumé,Achats,${data.purchases}", en: "Summary,Purchases,${data.purchases}" },
  "ملخص,الرواتب,${data.salaries}": { fr: "Résumé,Salaires,${data.salaries}", en: "Summary,Salaries,${data.salaries}" },
  "ملخص,مصاريف التشغيل,${data.operatingExpenses}": { fr: "Résumé,Dépenses d'exploitation,${data.operatingExpenses}", en: "Summary,Operating Expenses,${data.operatingExpenses}" },
  "ملخص,الهدر,${data.waste}": { fr: "Résumé,Gaspillage,${data.waste}", en: "Summary,Waste,${data.waste}" },
  "ملخص,صافي الربح,${net}": { fr: "Résumé,Bénéfice net,${net}", en: "Summary,Net Profit,${net}" },
  "الأصناف الأكثر مبيعاً,الكمية,الإيرادات": { fr: "Articles les plus vendus,Quantité,Revenus", en: "Best-selling items,Quantity,Revenue" },
  "أكثر مكوّن مهدور,التكلفة,الكمية": { fr: "Ingrédient le plus gaspillé,Coût,Quantité", en: "Most wasted ingredient,Cost,Quantity" },
  "<!doctype html><html dir=\"rtl\" lang=\"ar\"><head><meta charset=\"utf-8\"/>\n      <title>الربح الحقيقي — ${labelOf[range]}</title>\n      <style>\n        body{font-family:Cairo,system-ui,sans-serif;padding:24px;color:#111}\n        h1{margin:0 0 12px}\n        table{width:100%;border-collapse:collapse;font-size:14px}\n        td{padding:8px 10px;border-bottom:1px solid #eee}\n        .total{font-weight:bold;font-size:18px;background:#fafafa}\n        .pos{color:#16a34a} .neg{color:#dc2626}\n      </style></head><body>\n      <h1>تقرير الربح الحقيقي — ${labelOf[range]}</h1>\n      <table>\n        <tr><td>إجمالي الإيرادات</td><td style=\"text-align:left\" class=\"pos\">+ ${fmt(data.revenue)} دج</td></tr>\n        <tr><td>مصاريف التشغيل</td><td style=\"text-align:left\" class=\"neg\">- ${fmt(data.operatingExpenses)} دج</td></tr>\n        <tr><td>مشتريات الموردين</td><td style=\"text-align:left\" class=\"neg\">- ${fmt(data.purchases)} دج</td></tr>\n        <tr><td>رواتب الموظفين</td><td style=\"text-align:left\" class=\"neg\">- ${fmt(data.salaries)} دج</td></tr>\n        <tr><td>تكلفة الهدر</td><td style=\"text-align:left\" class=\"neg\">- ${fmt(data.waste)} دج</td></tr>\n        <tr class=\"total\"><td>${net >= 0 ? \"الربح الصافي\" : \"الخسارة الصافية\"}</td>\n          <td style=\"text-align:left\" class=\"${net >= 0 ? \"pos\" : \"neg\"}\">${fmt(net)} دج</td></tr>\n      </table>\n      <script>window.onload=()=>setTimeout(()=>window.print(),300)</script>\n      </body></html>": { fr: "<!doctype html><html dir=\"rtl\" lang=\"ar\"><head><meta charset=\"utf-8\"/>\n      <title>Bénéfice Réel — ${labelOf[range]}</title>\n      <style>\n        body{font-family:Cairo,system-ui,sans-serif;padding:24px;color:#111}\n        h1{margin:0 0 12px}\n        table{width:100%;border-collapse:collapse;font-size:14px}\n        td{padding:8px 10px;border-bottom:1px solid #eee}\n        .total{font-weight:bold;font-size:18px;background:#fafafa}\n        .pos{color:#16a34a} .neg{color:#dc2626}\n      </style></head><body>\n      <h1>Rapport de Bénéfice Réel — ${labelOf[range]}</h1>\n      <table>\n        <tr><td>Revenus Totaux</td><td style=\"text-align:left\" class=\"pos\">+ ${fmt(data.revenue)} دج</td></tr>\n        <tr><td>Dépenses d'exploitation</td><td style=\"text-align:left\" class=\"neg\">- ${fmt(data.operatingExpenses)} دج</td></tr>\n        <tr><td>Achats Fournisseurs</td><td style=\"text-align:left\" class=\"neg\">- ${fmt(data.purchases)} دج</td></tr>\n        <tr><td>Salaires des Employés</td><td style=\"text-align:left\" class=\"neg\">- ${fmt(data.salaries)} دج</td></tr>\n        <tr><td>Coût du Gaspillage</td><td style=\"text-align:left\" class=\"neg\">- ${fmt(data.waste)} دج</td></tr>\n        <tr class=\"total\"><td>${net >= 0 ? \"Bénéfice Net\" : \"Perte Nette\"}</td>\n          <td style=\"text-align:left\" class=\"${net >= 0 ? \"pos\" : \"neg\"}\">${fmt(net)} دج</td></tr>\n      </table>\n      <script>window.onload=()=>setTimeout(()=>window.print(),300)</script>\n      </body></html>", en: "<!doctype html><html dir=\"rtl\" lang=\"ar\"><head><meta charset=\"utf-8\"/>\n      <title>True Profit — ${labelOf[range]}</title>\n      <style>\n        body{font-family:Cairo,system-ui,sans-serif;padding:24px;color:#111}\n        h1{margin:0 0 12px}\n        table{width:100%;border-collapse:collapse;font-size:14px}\n        td{padding:8px 10px;border-bottom:1px solid #eee}\n        .total{font-weight:bold;font-size:18px;background:#fafafa}\n        .pos{color:#16a34a} .neg{color:#dc2626}\n      </style></head><body>\n      <h1>True Profit Report — ${labelOf[range]}</h1>\n      <table>\n        <tr><td>Total Revenue</td><td style=\"text-align:left\" class=\"pos\">+ ${fmt(data.revenue)} دج</td></tr>\n        <tr><td>Operating Expenses</td><td style=\"text-align:left\" class=\"neg\">- ${fmt(data.operatingExpenses)} دج</td></tr>\n        <tr><td>Supplier Purchases</td><td style=\"text-align:left\" class=\"neg\">- ${fmt(data.purchases)} دج</td></tr>\n        <tr><td>Employee Salaries</td><td style=\"text-align:left\" class=\"neg\">- ${fmt(data.salaries)} دج</td></tr>\n        <tr><td>Cost of Waste</td><td style=\"text-align:left\" class=\"neg\">- ${fmt(data.waste)} دج</td></tr>\n        <tr class=\"total\"><td>${net >= 0 ? \"Net Profit\" : \"Net Loss\"}</td>\n          <td style=\"text-align:left\" class=\"${net >= 0 ? \"pos\" : \"neg\"}\">${fmt(net)} دج</td></tr>\n      </table>\n      <script>window.onload=()=>setTimeout(()=>window.print(),300)</script>\n      </body></html>" },
  "${fmt(data.revenue)} دج": { fr: "${fmt(data.revenue)} دج", en: "${fmt(data.revenue)} دج" },
  "${data.ordersCount} طلب مدفوع": { fr: "${data.ordersCount} commandes payées", en: "${data.ordersCount} paid orders" },
  "${fmt(expenses)} دج": { fr: "${fmt(expenses)} دج", en: "${fmt(expenses)} دج" },
  "مشتريات + رواتب + هدر": { fr: "Achats + salaires + gaspillage", en: "Purchases + salaries + waste" },
  "${fmt(net)} دج": { fr: "${fmt(net)} دج", en: "${fmt(net)} دج" },
  "${((net / data.revenue) * 100).toFixed(1)}% هامش": { fr: "${((net / data.revenue) * 100).toFixed(1)}% marge", en: "${((net / data.revenue) * 100).toFixed(1)}% margin" },
  "${fmt(data.waste)} دج": { fr: "${fmt(data.waste)} دج", en: "${fmt(data.waste)} دج" },
  "${((data.waste / data.revenue) * 100).toFixed(1)}% من الإيراد": { fr: "${((data.waste / data.revenue) * 100).toFixed(1)}% des revenus", en: "${((data.waste / data.revenue) * 100).toFixed(1)}% of revenue" },
  "${fmt(data.topSupplier.total)} دج": { fr: "${fmt(data.topSupplier.total)} دج", en: "${fmt(data.topSupplier.total)} دج" },
  "لا توجد مشتريات": { fr: "Pas d'achats", en: "No purchases" },
  "التقارير المالية": { fr: "Rapports financiers", en: "Financial Reports" },
  "الربح الحقيقي": { fr: "Bénéfice réel", en: "Real Profit" },
  "الأصناف الأكثر مبيعاً": { fr: "Articles les plus vendus", en: "Best-selling items" },
  "أكثر مكوّن مهدور": { fr: "Ingrédient le plus gaspillé", en: "Most wasted ingredient" },
  "المورد الأكثر اعتماداً": { fr: "Fournisseur le plus fiable", en: "Most relied-upon supplier" },
  "تفاصيل المصاريف": { fr: "Détails des dépenses", en: "Expense Details" },
  "${stats.length} موظف": { fr: "${stats.length} employés", en: "${stats.length} employees" },
  "${s.avgPrepMin.toFixed(1)} د": { fr: "${s.avgPrepMin.toFixed(1)} min", en: "${s.avgPrepMin.toFixed(1)} min" },
  "من": { fr: "De", en: "From" },
  "إلى": { fr: "À", en: "To" },
  "نُدُل (مبيعات)": { fr: "Serveurs (ventes)", en: "Waiters (Sales)" },
  "مطبخ (وقت التحضير)": { fr: "Cuisine (temps de préparation)", en: "Kitchen (Prep time)" },
  "المبيعات لكل موظف": { fr: "Ventes par employé", en: "Sales per Employee" },
  "عدد الطلبات": { fr: "Nombre de commandes", en: "Number of Orders" },
  "إجمالي المبيعات": { fr: "Ventes totales", en: "Total Sales" },
  "متوسط الفاتورة": { fr: "Facture moyenne", en: "Average Invoice" },
  "متوسط وقت التحضير": { fr: "Temps de préparation moyen", en: "Average Prep Time" },
  "اسم المورد مطلوب": { fr: "Nom du fournisseur requis", en: "Supplier name required" },
  "تمت إضافة المورد": { fr: "Fournisseur ajouté", en: "Supplier added" },
  "حذف \"${s.name}\"؟ لن يتأثر سجل الفواتير السابقة.": { fr: "Supprimer \"${s.name}\" ? L'historique des factures précédentes ne sera pas affecté.", en: "Delete \"${s.name}\"? Previous invoice history will not be affected." },
  "فشل الحذف — قد يكون مرتبطاً بفواتير": { fr: "Échec de la suppression — peut être lié à des factures", en: "Deletion failed — may be linked to invoices" },
  "أدخل اسم المورد الجديد": { fr: "Saisissez le nom du nouveau fournisseur", en: "Enter new supplier name" },
  "فشل إضافة المورد الجديد": { fr: "Échec de l'ajout du nouveau fournisseur", en: "Failed to add new supplier" },
  "أضف صفاً واحداً على الأقل": { fr: "Ajoutez au moins une ligne", en: "Add at least one row" },
  "فشل إنشاء الفاتورة": { fr: "Échec de la création de la facture", en: "Failed to create invoice" },
  "فشل حفظ بنود الفاتورة": { fr: "Échec de l'enregistrement des éléments de la facture", en: "Failed to save invoice items" },
  "فاتورة شراء #${po.id.slice(0, 8)}": { fr: "Facture d'achat n°{{po.id.slice(0, 8)}}", en: "Purchase Invoice #{{po.id.slice(0, 8)}}" },
  "تم تسجيل الفاتورة وتحديث المخزون": { fr: "Facture enregistrée et stock mis à jour", en: "Invoice recorded and inventory updated" },
  "متوازن": { fr: "Équilibré", en: "Balanced" },
  "مدين (لنا عليه)": { fr: "Débiteur (nous devons)", en: "Debtor (owes us)" },
  "دائن (لهم علينا)": { fr: "Créditeur (nous leur devons)", en: "Creditor (we owe them)" },
  "لا يوجد موردون — اختر «مورد جديد»": { fr: "Pas de fournisseurs — Choisissez «Nouveau fournisseur»", en: "No suppliers — Choose 'New Supplier'" },
  "اسم المورد الجديد (سيُضاف تلقائياً)": { fr: "Nom du nouveau fournisseur (sera ajouté automatiquement)", en: "New supplier name (will be added automatically)" },
  "مكون": { fr: "Ingrédient", en: "Ingredient" },
  "سعر/وحدة": { fr: "Prix/unité", en: "Price/unit" },
  "حفظ الفاتورة": { fr: "Enregistrer la facture", en: "Save Invoice" },
  "كشف حساب": { fr: "Relevé de compte", en: "Account Statement" },
  "عدد الفواتير": { fr: "Nombre de factures", en: "Number of Invoices" },
  "المجموع الكلي": { fr: "Total général", en: "Grand Total" },
  "0 ? \"مدين (لنا عليه)\" : \"دائن (لهم علينا)\";\n                  return (": { fr: "0 ? \"Débiteur (nous devons)\" : \"Créditeur (nous leur devons)\"; return (", en: "0 ? \"Debtor (owes us)\" : \"Creditor (we owe them)\"; return (" },
  "آخر الفواتير:": { fr: "Dernières factures:", en: "Last Invoices:" },
  "تعديل المورد": { fr: "Modifier le fournisseur", en: "Edit Supplier" },
  "المورد": { fr: "Fournisseur", en: "Supplier" },
  "مورد جديد": { fr: "Nouveau fournisseur", en: "New Supplier" },
  "البنود": { fr: "Articles", en: "Items" },
  "صف": { fr: "Ligne", en: "Row" },
  "ملاحظات (اختياري)": { fr: "Notes (facultatif)", en: "Notes (optional)" },
  "نظرة عامة": { fr: "Aperçu", en: "Overview" },
  "المخزون": { fr: "Inventaire", en: "Inventory" },
  "الوصفات": { fr: "Recettes", en: "Recipes" },
  "الموردين": { fr: "Fournisseurs", en: "Suppliers" },
  "أداء الموظفين": { fr: "Performance du personnel", en: "Staff Performance" },
  "العملاء والولاء": { fr: "Clients et fidélité", en: "Customers and Loyalty" },
  "الشكاوى": { fr: "Plaintes", en: "Complaints" },
  "التقارير": { fr: "Rapports", en: "Reports" },
  "إدارة العمليات": { fr: "Gestion des opérations", en: "Operations Management" },
  "لوحة التحكم": { fr: "Tableau de bord", en: "Dashboard" },
  "خروج": { fr: "Déconnexion", en: "Logout" },
  "إدارة العمليات اليومية": { fr: "Gérer les opérations quotidiennes", en: "Manage Daily Operations" },
  "فشل التحميل": { fr: "Échec du chargement", en: "Failed to Load" },
  "اختر المكون": { fr: "Sélectionner l'ingrédient", en: "Select Ingredient" },
  "الكمية غير صحيحة": { fr: "Quantité incorrecte", en: "Incorrect Quantity" },
  "تم التسجيل": { fr: "Enregistré", en: "Recorded" },
  "اختر مكوّن...": { fr: "Sélectionnez un ingrédient...", en: "Select an ingredient..." },
  "تكلفة الهدر — الأسبوع": { fr: "Coût du gaspillage — Semaine", en: "Waste Cost — Week" },
  "تكلفة الهدر — 30 يوم": { fr: "Coût du gaspillage — 30 jours", en: "Waste Cost — 30 Days" },
  "السبب الأكثر تكلفة": { fr: "La raison la plus coûteuse", en: "Most Costly Reason" },
  "سجّله": { fr: "Enregistrer", en: "Record It" },
  "التكلفة": { fr: "Coût", en: "Cost" },
  "حذف \"": { fr: "Supprimer ", en: "Delete " },
  "\"؟ سجل الرواتب سيُحذف معه.": { fr: " ? La fiche de paie sera également supprimée.", en: "? The payroll will be deleted with it." },
  "تم نسخ ": { fr: "Copié ", en: "Copied " },
  " مصروف": { fr: " dépense", en: " expense" },
  "<!doctype html><html dir=\"rtl\" lang=\"ar\"><head><meta charset=\"utf-8\"/>\n      <title>تقرير الربح — ": { fr: "<!doctype html><html dir=\"rtl\" lang=\"ar\"><head><meta charset=\"utf-8\"/><title>Rapport de profit — ", en: "<!doctype html><html dir=\"rtl\" lang=\"ar\"><head><meta charset=\"utf-8\"/><title>Profit report — " },
  "</title>\n      <style>\n        body{font-family:Cairo,system-ui,sans-serif;padding:24px;color:#111}\n        h1{margin:0 0 12px}\n        table{width:100%;border-collapse:collapse;font-size:14px}\n        td{padding:8px 10px;border-bottom:1px solid #eee}\n        .total{font-weight:bold;font-size:18px;background:#fafafa}\n        .pos{color:#16a34a} .neg{color:#dc2626}\n      </style></head><body>\n      <h1>تقرير الربح الحقيقي — ": { fr: "</title><style>body{font-family:Cairo,system-ui,sans-serif;padding:24px;color:#111}h1{margin:0 0 12px}table{width:100%;border-collapse:collapse;font-size:14px}td{padding:8px 10px;border-bottom:1px solid #eee}.total{font-weight:bold;font-size:18px;background:#fafafa}.pos{color:#16a34a} .neg{color:#dc2626}</style></head><body><h1>Rapport de profit réel — ", en: "</title><style>body{font-family:Cairo,system-ui,sans-serif;padding:24px;color:#111}h1{margin:0 0 12px}table{width:100%;border-collapse:collapse;font-size:14px}td{padding:8px 10px;border-bottom:1px solid #eee}.total{font-weight:bold;font-size:18px;background:#fafafa}.pos{color:#16a34a} .neg{color:#dc2626}</style></head><body><h1>Real Profit Report — " },
  "</h1>\n      <table>\n        <tr><td>{tx(\"إجمالي الإيرادات\")}</td><td style=\"text-align:left\" class=\"pos\">+ ": { fr: "</h1><table><tr><td>{tx(\"Total des revenus\")}</td><td style=\"text-align:left\" class=\"pos\">+ ", en: "</h1><table><tr><td>{tx(\"Total Revenue\")}</td><td style=\"text-align:left\" class=\"pos\">+ " },
  "</td></tr>\n        <tr><td>{tx(\"مصاريف التشغيل\")}</td><td style=\"text-align:left\" class=\"neg\">- ": { fr: "</td></tr><tr><td>{tx(\"Dépenses de fonctionnement\")}</td><td style=\"text-align:left\" class=\"neg\">- ", en: "</td></tr><tr><td>{tx(\"Operating Expenses\")}</td><td style=\"text-align:left\" class=\"neg\">- " },
  "</td></tr>\n        <tr><td>{tx(\"مشتريات الموردين\")}</td><td style=\"text-align:left\" class=\"neg\">- ": { fr: "</td></tr><tr><td>{tx(\"Achats fournisseurs\")}</td><td style=\"text-align:left\" class=\"neg\">- ", en: "</td></tr><tr><td>{tx(\"Supplier Purchases\")}</td><td style=\"text-align:left\" class=\"neg\">- " },
  "</td></tr>\n        <tr><td>{tx(\"رواتب العمال\")}</td><td style=\"text-align:left\" class=\"neg\">- ": { fr: "</td></tr><tr><td>{tx(\"Salaires des employés\")}</td><td style=\"text-align:left\" class=\"neg\">- ", en: "</td></tr><tr><td>{tx(\"Employee Salaries\")}</td><td style=\"text-align:left\" class=\"neg\">- " },
  " دج": { fr: " DA", en: " DZD" },
  "فشل إضافة المكون: ": { fr: "Échec de l'ajout de l'ingrédient : ", en: "Failed to add ingredient: " },
  "تم استخراج ": { fr: "Extrait ", en: "Extracted " },
  " عنصر": { fr: " article", en: " item" },
  "فاتورة مصورة": { fr: "Facture avec photo", en: "Invoiced photo" },
  "فاتورة مصورة #": { fr: "Facture avec photo #", en: "Invoiced photo #" },
  "تمت إضافة ": { fr: "Ajouté ", en: "Added " },
  " مكون للمخزون": { fr: " ingrédient au stock", en: " ingredient to stock" },
  "\"؟ لا يمكن التراجع.": { fr: " ? Cette action est irréversible.", en: "? This cannot be undone." },
  "حفظ (": { fr: "Enregistrer (", en: "Save (" },
  " مكوّن": { fr: " ingrédient", en: " ingredient" },
  "الفترة,": { fr: "Période,", en: "Period," },
  "ملخص,الإيرادات (طلبات مدفوعة),": { fr: "Résumé,Revenus (commandes payées),", en: "Summary,Revenue (paid orders)," },
  "ملخص,المشتريات,": { fr: "Résumé,Achats,", en: "Summary,Purchases," },
  "ملخص,الرواتب,": { fr: "Résumé,Salaires,", en: "Summary,Salaries," },
  "ملخص,مصاريف التشغيل,": { fr: "Résumé,Dépenses d'exploitation,", en: "Summary,Operating expenses," },
  "ملخص,الهدر,": { fr: "Résumé,Gaspillage,", en: "Summary,Waste," },
  "ملخص,صافي الربح,": { fr: "Résumé,Bénéfice net,", en: "Summary,Net profit," },
  "<!doctype html><html dir=\"rtl\" lang=\"ar\"><head><meta charset=\"utf-8\"/>\n      <title>الربح الحقيقي — ": { fr: "<!doctype html><html dir=\"rtl\" lang=\"ar\"><head><meta charset=\"utf-8\"/>\n      <title>Bénéfice réel — ", en: "<!doctype html><html dir=\"rtl\" lang=\"ar\"><head><meta charset=\"utf-8\"/>\n      <title>Real Profit — " },
  " دج</td></tr>\n        <tr><td>{tx(\"مصاريف التشغيل\")}</td><td style=\"text-align:left\" class=\"neg\">- ": { fr: " DA</td></tr>\n        <tr><td>{tx(\"Dépenses d'exploitation\")}</td><td style=\"text-align:left\" class=\"neg\">- ", en: " DA</td></tr>\n        <tr><td>{tx(\"Operating expenses\")}</td><td style=\"text-align:left\" class=\"neg\">- " },
  " دج</td></tr>\n        <tr><td>{tx(\"مشتريات الموردين\")}</td><td style=\"text-align:left\" class=\"neg\">- ": { fr: " DA</td></tr>\n        <tr><td>{tx(\"Achats fournisseurs\")}</td><td style=\"text-align:left\" class=\"neg\">- ", en: " DA</td></tr>\n        <tr><td>{tx(\"Supplier purchases\")}</td><td style=\"text-align:left\" class=\"neg\">- " },
  " دج</td></tr>\n        <tr><td>{tx(\"رواتب الموظفين\")}</td><td style=\"text-align:left\" class=\"neg\">- ": { fr: " DA</td></tr>\n        <tr><td>{tx(\"Salaires des employés\")}</td><td style=\"text-align:left\" class=\"neg\">- ", en: " DA</td></tr>\n        <tr><td>{tx(\"Employee salaries\")}</td><td style=\"text-align:left\" class=\"neg\">- " },
  " دج</td></tr>\n        <tr><td>{tx(\"تكلفة الهدر\")}</td><td style=\"text-align:left\" class=\"neg\">- ": { fr: " DA</td></tr>\n        <tr><td>{tx(\"Coût du gaspillage\")}</td><td style=\"text-align:left\" class=\"neg\">- ", en: " DA</td></tr>\n        <tr><td>{tx(\"Cost of waste\")}</td><td style=\"text-align:left\" class=\"neg\">- " },
  " دج</td></tr>\n        <tr class=\"total\"><td>": { fr: " DA</td></tr>\n        <tr class=\"total\"><td>", en: " DA</td></tr>\n        <tr class=\"total\"><td>" },
  " دج</td></tr>\n      </table>\n      <script>window.onload=()=>setTimeout(()=>window.print(),300)</script>\n      </body></html>": { fr: " DA</td></tr>\n      </table>\n      <script>window.onload=()=>setTimeout(()=>window.print(),300)</script>\n      </body></html>", en: " DA</td></tr>\n      </table>\n      <script>window.onload=()=>setTimeout(()=>window.print(),300)</script>\n      </body></html>" },
  " طلب مدفوع": { fr: " commande payée", en: " paid order" },
  "% هامش": { fr: "% marge", en: "% margin" },
  "% من الإيراد": { fr: "% du revenu", en: "% of revenue" },
  " موظف": { fr: " employé", en: " employee" },
  " د": { fr: " D", en: " D" },
  "\"؟ لن يتأثر سجل الفواتير السابقة.": { fr: " ? L'historique des factures précédentes ne sera pas affecté.", en: " ? Previous invoice history will not be affected." },
  "فاتورة شراء #": { fr: "Facture d'achat #", en: "Purchase Invoice #" },
  "لتعديل الكمية الحالية، استخدم \"إضافة/خصم من المخزون\".": { fr: "Pour ajuster la quantité actuelle, utilisez \"Ajouter/Déduire du stock\".", en: "To adjust the current quantity, use \"Add/Deduct from Stock\"." },
  "جاري التحميل...": { fr: "Chargement...", en: "Loading..." },
  "لا يوجد موظفين بعد": { fr: "Pas encore d'employés", en: "No employees yet" },
  "مدفوع": { fr: "Payé", en: "Paid" },
  "لا توجد مدفوعات بعد": { fr: "Pas encore de paiements", en: "No payments yet" },
  "لا توجد مكونات بعد": { fr: "Pas encore d'ingrédients", en: "No ingredients yet" },
  "ارفع صورة الفاتورة وسيتم استخراج العناصر تلقائياً وإضافتها للمخزون.": { fr: "Téléchargez une photo de la facture et les articles seront automatiquement extraits et ajoutés au stock.", en: "Upload a photo of the invoice and items will be automatically extracted and added to stock." },
  "وصفات الأصناف": { fr: "Recettes d'articles", en: "Item Recipes" },
  "اربط كل صنف بالمكونات المستهلكة. عند تأكيد الدفع يُنقص المخزون تلقائياً.": { fr: "Lie chaque article aux ingrédients consommés. Lors de la confirmation du paiement, le stock est automatiquement déduit.", en: "Link each item to the consumed ingredients. Upon payment confirmation, stock is automatically deducted." },
  "لا توجد أصناف.": { fr: "Pas d'articles.", en: "No items." },
  "أداء المطعم: إيرادات، مصاريف، ربح، وأكثر الأصناف والمكونات.": { fr: "Performance du restaurant : revenus, dépenses, bénéfices et articles et ingrédients les plus populaires.", en: "Restaurant performance: revenue, expenses, profit, and top items and ingredients." },
  "ملاحظة: تعتمد الإحصائيات على ربط الطلبات بالموظفين (أُضيف الحقل حديثاً ولا يكسر إنشاء الطلبات الحالي).": { fr: "Remarque : les statistiques sont basées sur la liaison des commandes aux employés (le champ a été récemment ajouté et n'interfère pas avec la création de commandes existante).", en: "Note: Statistics are based on linking orders to employees (field was recently added and does not break existing order creation)." },
  "لا يوجد موردين بعد": { fr: "Pas encore de fournisseurs", en: "No suppliers yet" },
  "من القائمة": { fr: "Du menu", en: "From the menu" },
  "لا يوجد تسجيلات بعد": { fr: "Pas encore d'enregistrements", en: "No records yet" },
  "مصاريف التشغيل:": { fr: "Frais d'exploitation:", en: "Operating expenses:" },
  "مشتريات:": { fr: "Achats:", en: "Purchases:" },
  "رواتب:": { fr: "Salaires:", en: "Salaries:" },
  "هدر:": { fr: "Gaspillage:", en: "Waste:" },
  "دج": { fr: "DZD", en: "DZD" },
};

export function tx(ar: string): string {
  const lng = (i18n.language || "ar").split("-")[0];
  if (lng === "ar") return ar;
  const entry = dict[ar];
  if (!entry) return ar;
  if (lng === "fr") return entry.fr;
  if (lng === "en") return entry.en;
  return ar;
}
