/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaiterScreenRouteImport } from './routes/waiter-screen'
import { Route as WaiterLoginRouteImport } from './routes/waiter-login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OpsRouteImport } from './routes/ops'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KitchenScreenRouteImport } from './routes/kitchen-screen'
import { Route as KitchenLoginRouteImport } from './routes/kitchen-login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CashierLoginRouteImport } from './routes/cashier-login'
import { Route as CashierRouteImport } from './routes/cashier'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OpsIndexRouteImport } from './routes/ops.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as TTakeaway_tokenRouteImport } from './routes/t.$takeaway_token'
import { Route as RQr_tokenRouteImport } from './routes/r.$qr_token'
import { Route as OpsWasteRouteImport } from './routes/ops.waste'
import { Route as OpsSuppliersRouteImport } from './routes/ops.suppliers'
import { Route as OpsStaffPerformanceRouteImport } from './routes/ops.staff-performance'
import { Route as OpsReportsRouteImport } from './routes/ops.reports'
import { Route as OpsRecipesRouteImport } from './routes/ops.recipes'
import { Route as OpsInventoryCountRouteImport } from './routes/ops.inventory-count'
import { Route as OpsInventoryRouteImport } from './routes/ops.inventory'
import { Route as OpsExpensesRouteImport } from './routes/ops.expenses'
import { Route as OpsEmployeesRouteImport } from './routes/ops.employees'
import { Route as OpsCustomersRouteImport } from './routes/ops.customers'
import { Route as OpsComplaintsRouteImport } from './routes/ops.complaints'
import { Route as DashboardTablesRouteImport } from './routes/dashboard.tables'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardReviewsRouteImport } from './routes/dashboard.reviews'
import { Route as DashboardOrdersRouteImport } from './routes/dashboard.orders'
import { Route as DashboardMenuRouteImport } from './routes/dashboard.menu'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard.analytics'
import { Route as DDelivery_tokenRouteImport } from './routes/d.$delivery_token'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'
import { Route as ApiPublicHooksDeliveryFollowupRouteImport } from './routes/api/public/hooks/delivery-followup'
import { Route as ApiPublicHooksDailySummaryRouteImport } from './routes/api/public/hooks/daily-summary'
import { Route as ApiPublicTelegramWebhookRidRouteImport } from './routes/api/public/telegram/webhook.$rid'
import { Route as ApiPublicTelegramSummaryWebhookRidRouteImport } from './routes/api/public/telegram/summary-webhook.$rid'

const WaiterScreenRoute = WaiterScreenRouteImport.update({
  id: '/waiter-screen',
  path: '/waiter-screen',
  getParentRoute: () => rootRouteImport,
} as any)
const WaiterLoginRoute = WaiterLoginRouteImport.update({
  id: '/waiter-login',
  path: '/waiter-login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsRoute = OpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenScreenRoute = KitchenScreenRouteImport.update({
  id: '/kitchen-screen',
  path: '/kitchen-screen',
  getParentRoute: () => rootRouteImport,
} as any)
const KitchenLoginRoute = KitchenLoginRouteImport.update({
  id: '/kitchen-login',
  path: '/kitchen-login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CashierLoginRoute = CashierLoginRouteImport.update({
  id: '/cashier-login',
  path: '/cashier-login',
  getParentRoute: () => rootRouteImport,
} as any)
const CashierRoute = CashierRouteImport.update({
  id: '/cashier',
  path: '/cashier',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsIndexRoute = OpsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OpsRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const TTakeaway_tokenRoute = TTakeaway_tokenRouteImport.update({
  id: '/t/$takeaway_token',
  path: '/t/$takeaway_token',
  getParentRoute: () => rootRouteImport,
} as any)
const RQr_tokenRoute = RQr_tokenRouteImport.update({
  id: '/r/$qr_token',
  path: '/r/$qr_token',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsWasteRoute = OpsWasteRouteImport.update({
  id: '/waste',
  path: '/waste',
  getParentRoute: () => OpsRoute,
} as any)
const OpsSuppliersRoute = OpsSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => OpsRoute,
} as any)
const OpsStaffPerformanceRoute = OpsStaffPerformanceRouteImport.update({
  id: '/staff-performance',
  path: '/staff-performance',
  getParentRoute: () => OpsRoute,
} as any)
const OpsReportsRoute = OpsReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => OpsRoute,
} as any)
const OpsRecipesRoute = OpsRecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => OpsRoute,
} as any)
const OpsInventoryCountRoute = OpsInventoryCountRouteImport.update({
  id: '/inventory-count',
  path: '/inventory-count',
  getParentRoute: () => OpsRoute,
} as any)
const OpsInventoryRoute = OpsInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => OpsRoute,
} as any)
const OpsExpensesRoute = OpsExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => OpsRoute,
} as any)
const OpsEmployeesRoute = OpsEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => OpsRoute,
} as any)
const OpsCustomersRoute = OpsCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => OpsRoute,
} as any)
const OpsComplaintsRoute = OpsComplaintsRouteImport.update({
  id: '/complaints',
  path: '/complaints',
  getParentRoute: () => OpsRoute,
} as any)
const DashboardTablesRoute = DashboardTablesRouteImport.update({
  id: '/tables',
  path: '/tables',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReviewsRoute = DashboardReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrdersRoute = DashboardOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMenuRoute = DashboardMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DDelivery_tokenRoute = DDelivery_tokenRouteImport.update({
  id: '/d/$delivery_token',
  path: '/d/$delivery_token',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDeliveryFollowupRoute =
  ApiPublicHooksDeliveryFollowupRouteImport.update({
    id: '/api/public/hooks/delivery-followup',
    path: '/api/public/hooks/delivery-followup',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksDailySummaryRoute =
  ApiPublicHooksDailySummaryRouteImport.update({
    id: '/api/public/hooks/daily-summary',
    path: '/api/public/hooks/daily-summary',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTelegramWebhookRidRoute =
  ApiPublicTelegramWebhookRidRouteImport.update({
    id: '/$rid',
    path: '/$rid',
    getParentRoute: () => ApiPublicTelegramWebhookRoute,
  } as any)
const ApiPublicTelegramSummaryWebhookRidRoute =
  ApiPublicTelegramSummaryWebhookRidRouteImport.update({
    id: '/api/public/telegram/summary-webhook/$rid',
    path: '/api/public/telegram/summary-webhook/$rid',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cashier': typeof CashierRoute
  '/cashier-login': typeof CashierLoginRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/kitchen-login': typeof KitchenLoginRoute
  '/kitchen-screen': typeof KitchenScreenRoute
  '/login': typeof LoginRoute
  '/ops': typeof OpsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/waiter-login': typeof WaiterLoginRoute
  '/waiter-screen': typeof WaiterScreenRoute
  '/d/$delivery_token': typeof DDelivery_tokenRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/menu': typeof DashboardMenuRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/tables': typeof DashboardTablesRoute
  '/ops/complaints': typeof OpsComplaintsRoute
  '/ops/customers': typeof OpsCustomersRoute
  '/ops/employees': typeof OpsEmployeesRoute
  '/ops/expenses': typeof OpsExpensesRoute
  '/ops/inventory': typeof OpsInventoryRoute
  '/ops/inventory-count': typeof OpsInventoryCountRoute
  '/ops/recipes': typeof OpsRecipesRoute
  '/ops/reports': typeof OpsReportsRoute
  '/ops/staff-performance': typeof OpsStaffPerformanceRoute
  '/ops/suppliers': typeof OpsSuppliersRoute
  '/ops/waste': typeof OpsWasteRoute
  '/r/$qr_token': typeof RQr_tokenRoute
  '/t/$takeaway_token': typeof TTakeaway_tokenRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/ops/': typeof OpsIndexRoute
  '/api/public/hooks/daily-summary': typeof ApiPublicHooksDailySummaryRoute
  '/api/public/hooks/delivery-followup': typeof ApiPublicHooksDeliveryFollowupRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRouteWithChildren
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/api/public/telegram/summary-webhook/$rid': typeof ApiPublicTelegramSummaryWebhookRidRoute
  '/api/public/telegram/webhook/$rid': typeof ApiPublicTelegramWebhookRidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cashier': typeof CashierRoute
  '/cashier-login': typeof CashierLoginRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/kitchen-login': typeof KitchenLoginRoute
  '/kitchen-screen': typeof KitchenScreenRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/waiter-login': typeof WaiterLoginRoute
  '/waiter-screen': typeof WaiterScreenRoute
  '/d/$delivery_token': typeof DDelivery_tokenRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/menu': typeof DashboardMenuRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/tables': typeof DashboardTablesRoute
  '/ops/complaints': typeof OpsComplaintsRoute
  '/ops/customers': typeof OpsCustomersRoute
  '/ops/employees': typeof OpsEmployeesRoute
  '/ops/expenses': typeof OpsExpensesRoute
  '/ops/inventory': typeof OpsInventoryRoute
  '/ops/inventory-count': typeof OpsInventoryCountRoute
  '/ops/recipes': typeof OpsRecipesRoute
  '/ops/reports': typeof OpsReportsRoute
  '/ops/staff-performance': typeof OpsStaffPerformanceRoute
  '/ops/suppliers': typeof OpsSuppliersRoute
  '/ops/waste': typeof OpsWasteRoute
  '/r/$qr_token': typeof RQr_tokenRoute
  '/t/$takeaway_token': typeof TTakeaway_tokenRoute
  '/dashboard': typeof DashboardIndexRoute
  '/ops': typeof OpsIndexRoute
  '/api/public/hooks/daily-summary': typeof ApiPublicHooksDailySummaryRoute
  '/api/public/hooks/delivery-followup': typeof ApiPublicHooksDeliveryFollowupRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRouteWithChildren
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/api/public/telegram/summary-webhook/$rid': typeof ApiPublicTelegramSummaryWebhookRidRoute
  '/api/public/telegram/webhook/$rid': typeof ApiPublicTelegramWebhookRidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cashier': typeof CashierRoute
  '/cashier-login': typeof CashierLoginRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/kitchen-login': typeof KitchenLoginRoute
  '/kitchen-screen': typeof KitchenScreenRoute
  '/login': typeof LoginRoute
  '/ops': typeof OpsRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/setup': typeof SetupRoute
  '/signup': typeof SignupRoute
  '/waiter-login': typeof WaiterLoginRoute
  '/waiter-screen': typeof WaiterScreenRoute
  '/d/$delivery_token': typeof DDelivery_tokenRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/menu': typeof DashboardMenuRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/reviews': typeof DashboardReviewsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/tables': typeof DashboardTablesRoute
  '/ops/complaints': typeof OpsComplaintsRoute
  '/ops/customers': typeof OpsCustomersRoute
  '/ops/employees': typeof OpsEmployeesRoute
  '/ops/expenses': typeof OpsExpensesRoute
  '/ops/inventory': typeof OpsInventoryRoute
  '/ops/inventory-count': typeof OpsInventoryCountRoute
  '/ops/recipes': typeof OpsRecipesRoute
  '/ops/reports': typeof OpsReportsRoute
  '/ops/staff-performance': typeof OpsStaffPerformanceRoute
  '/ops/suppliers': typeof OpsSuppliersRoute
  '/ops/waste': typeof OpsWasteRoute
  '/r/$qr_token': typeof RQr_tokenRoute
  '/t/$takeaway_token': typeof TTakeaway_tokenRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/ops/': typeof OpsIndexRoute
  '/api/public/hooks/daily-summary': typeof ApiPublicHooksDailySummaryRoute
  '/api/public/hooks/delivery-followup': typeof ApiPublicHooksDeliveryFollowupRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRouteWithChildren
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/api/public/telegram/summary-webhook/$rid': typeof ApiPublicTelegramSummaryWebhookRidRoute
  '/api/public/telegram/webhook/$rid': typeof ApiPublicTelegramWebhookRidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cashier'
    | '/cashier-login'
    | '/dashboard'
    | '/forgot-password'
    | '/kitchen-login'
    | '/kitchen-screen'
    | '/login'
    | '/ops'
    | '/reset-password'
    | '/setup'
    | '/signup'
    | '/waiter-login'
    | '/waiter-screen'
    | '/d/$delivery_token'
    | '/dashboard/analytics'
    | '/dashboard/menu'
    | '/dashboard/orders'
    | '/dashboard/reviews'
    | '/dashboard/settings'
    | '/dashboard/tables'
    | '/ops/complaints'
    | '/ops/customers'
    | '/ops/employees'
    | '/ops/expenses'
    | '/ops/inventory'
    | '/ops/inventory-count'
    | '/ops/recipes'
    | '/ops/reports'
    | '/ops/staff-performance'
    | '/ops/suppliers'
    | '/ops/waste'
    | '/r/$qr_token'
    | '/t/$takeaway_token'
    | '/dashboard/'
    | '/ops/'
    | '/api/public/hooks/daily-summary'
    | '/api/public/hooks/delivery-followup'
    | '/api/public/telegram/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/api/public/telegram/summary-webhook/$rid'
    | '/api/public/telegram/webhook/$rid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cashier'
    | '/cashier-login'
    | '/forgot-password'
    | '/kitchen-login'
    | '/kitchen-screen'
    | '/login'
    | '/reset-password'
    | '/setup'
    | '/signup'
    | '/waiter-login'
    | '/waiter-screen'
    | '/d/$delivery_token'
    | '/dashboard/analytics'
    | '/dashboard/menu'
    | '/dashboard/orders'
    | '/dashboard/reviews'
    | '/dashboard/settings'
    | '/dashboard/tables'
    | '/ops/complaints'
    | '/ops/customers'
    | '/ops/employees'
    | '/ops/expenses'
    | '/ops/inventory'
    | '/ops/inventory-count'
    | '/ops/recipes'
    | '/ops/reports'
    | '/ops/staff-performance'
    | '/ops/suppliers'
    | '/ops/waste'
    | '/r/$qr_token'
    | '/t/$takeaway_token'
    | '/dashboard'
    | '/ops'
    | '/api/public/hooks/daily-summary'
    | '/api/public/hooks/delivery-followup'
    | '/api/public/telegram/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/api/public/telegram/summary-webhook/$rid'
    | '/api/public/telegram/webhook/$rid'
  id:
    | '__root__'
    | '/'
    | '/cashier'
    | '/cashier-login'
    | '/dashboard'
    | '/forgot-password'
    | '/kitchen-login'
    | '/kitchen-screen'
    | '/login'
    | '/ops'
    | '/reset-password'
    | '/setup'
    | '/signup'
    | '/waiter-login'
    | '/waiter-screen'
    | '/d/$delivery_token'
    | '/dashboard/analytics'
    | '/dashboard/menu'
    | '/dashboard/orders'
    | '/dashboard/reviews'
    | '/dashboard/settings'
    | '/dashboard/tables'
    | '/ops/complaints'
    | '/ops/customers'
    | '/ops/employees'
    | '/ops/expenses'
    | '/ops/inventory'
    | '/ops/inventory-count'
    | '/ops/recipes'
    | '/ops/reports'
    | '/ops/staff-performance'
    | '/ops/suppliers'
    | '/ops/waste'
    | '/r/$qr_token'
    | '/t/$takeaway_token'
    | '/dashboard/'
    | '/ops/'
    | '/api/public/hooks/daily-summary'
    | '/api/public/hooks/delivery-followup'
    | '/api/public/telegram/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/api/public/telegram/summary-webhook/$rid'
    | '/api/public/telegram/webhook/$rid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CashierRoute: typeof CashierRoute
  CashierLoginRoute: typeof CashierLoginRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  KitchenLoginRoute: typeof KitchenLoginRoute
  KitchenScreenRoute: typeof KitchenScreenRoute
  LoginRoute: typeof LoginRoute
  OpsRoute: typeof OpsRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SetupRoute: typeof SetupRoute
  SignupRoute: typeof SignupRoute
  WaiterLoginRoute: typeof WaiterLoginRoute
  WaiterScreenRoute: typeof WaiterScreenRoute
  DDelivery_tokenRoute: typeof DDelivery_tokenRoute
  RQr_tokenRoute: typeof RQr_tokenRoute
  TTakeaway_tokenRoute: typeof TTakeaway_tokenRoute
  ApiPublicHooksDailySummaryRoute: typeof ApiPublicHooksDailySummaryRoute
  ApiPublicHooksDeliveryFollowupRoute: typeof ApiPublicHooksDeliveryFollowupRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRouteWithChildren
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  ApiPublicTelegramSummaryWebhookRidRoute: typeof ApiPublicTelegramSummaryWebhookRidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waiter-screen': {
      id: '/waiter-screen'
      path: '/waiter-screen'
      fullPath: '/waiter-screen'
      preLoaderRoute: typeof WaiterScreenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waiter-login': {
      id: '/waiter-login'
      path: '/waiter-login'
      fullPath: '/waiter-login'
      preLoaderRoute: typeof WaiterLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops': {
      id: '/ops'
      path: '/ops'
      fullPath: '/ops'
      preLoaderRoute: typeof OpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen-screen': {
      id: '/kitchen-screen'
      path: '/kitchen-screen'
      fullPath: '/kitchen-screen'
      preLoaderRoute: typeof KitchenScreenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kitchen-login': {
      id: '/kitchen-login'
      path: '/kitchen-login'
      fullPath: '/kitchen-login'
      preLoaderRoute: typeof KitchenLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cashier-login': {
      id: '/cashier-login'
      path: '/cashier-login'
      fullPath: '/cashier-login'
      preLoaderRoute: typeof CashierLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cashier': {
      id: '/cashier'
      path: '/cashier'
      fullPath: '/cashier'
      preLoaderRoute: typeof CashierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops/': {
      id: '/ops/'
      path: '/'
      fullPath: '/ops/'
      preLoaderRoute: typeof OpsIndexRouteImport
      parentRoute: typeof OpsRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/t/$takeaway_token': {
      id: '/t/$takeaway_token'
      path: '/t/$takeaway_token'
      fullPath: '/t/$takeaway_token'
      preLoaderRoute: typeof TTakeaway_tokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$qr_token': {
      id: '/r/$qr_token'
      path: '/r/$qr_token'
      fullPath: '/r/$qr_token'
      preLoaderRoute: typeof RQr_tokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops/waste': {
      id: '/ops/waste'
      path: '/waste'
      fullPath: '/ops/waste'
      preLoaderRoute: typeof OpsWasteRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/suppliers': {
      id: '/ops/suppliers'
      path: '/suppliers'
      fullPath: '/ops/suppliers'
      preLoaderRoute: typeof OpsSuppliersRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/staff-performance': {
      id: '/ops/staff-performance'
      path: '/staff-performance'
      fullPath: '/ops/staff-performance'
      preLoaderRoute: typeof OpsStaffPerformanceRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/reports': {
      id: '/ops/reports'
      path: '/reports'
      fullPath: '/ops/reports'
      preLoaderRoute: typeof OpsReportsRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/recipes': {
      id: '/ops/recipes'
      path: '/recipes'
      fullPath: '/ops/recipes'
      preLoaderRoute: typeof OpsRecipesRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/inventory-count': {
      id: '/ops/inventory-count'
      path: '/inventory-count'
      fullPath: '/ops/inventory-count'
      preLoaderRoute: typeof OpsInventoryCountRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/inventory': {
      id: '/ops/inventory'
      path: '/inventory'
      fullPath: '/ops/inventory'
      preLoaderRoute: typeof OpsInventoryRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/expenses': {
      id: '/ops/expenses'
      path: '/expenses'
      fullPath: '/ops/expenses'
      preLoaderRoute: typeof OpsExpensesRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/employees': {
      id: '/ops/employees'
      path: '/employees'
      fullPath: '/ops/employees'
      preLoaderRoute: typeof OpsEmployeesRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/customers': {
      id: '/ops/customers'
      path: '/customers'
      fullPath: '/ops/customers'
      preLoaderRoute: typeof OpsCustomersRouteImport
      parentRoute: typeof OpsRoute
    }
    '/ops/complaints': {
      id: '/ops/complaints'
      path: '/complaints'
      fullPath: '/ops/complaints'
      preLoaderRoute: typeof OpsComplaintsRouteImport
      parentRoute: typeof OpsRoute
    }
    '/dashboard/tables': {
      id: '/dashboard/tables'
      path: '/tables'
      fullPath: '/dashboard/tables'
      preLoaderRoute: typeof DashboardTablesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reviews': {
      id: '/dashboard/reviews'
      path: '/reviews'
      fullPath: '/dashboard/reviews'
      preLoaderRoute: typeof DashboardReviewsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/orders': {
      id: '/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof DashboardOrdersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/menu': {
      id: '/dashboard/menu'
      path: '/menu'
      fullPath: '/dashboard/menu'
      preLoaderRoute: typeof DashboardMenuRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/d/$delivery_token': {
      id: '/d/$delivery_token'
      path: '/d/$delivery_token'
      fullPath: '/d/$delivery_token'
      preLoaderRoute: typeof DDelivery_tokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/delivery-followup': {
      id: '/api/public/hooks/delivery-followup'
      path: '/api/public/hooks/delivery-followup'
      fullPath: '/api/public/hooks/delivery-followup'
      preLoaderRoute: typeof ApiPublicHooksDeliveryFollowupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/daily-summary': {
      id: '/api/public/hooks/daily-summary'
      path: '/api/public/hooks/daily-summary'
      fullPath: '/api/public/hooks/daily-summary'
      preLoaderRoute: typeof ApiPublicHooksDailySummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook/$rid': {
      id: '/api/public/telegram/webhook/$rid'
      path: '/$rid'
      fullPath: '/api/public/telegram/webhook/$rid'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRidRouteImport
      parentRoute: typeof ApiPublicTelegramWebhookRoute
    }
    '/api/public/telegram/summary-webhook/$rid': {
      id: '/api/public/telegram/summary-webhook/$rid'
      path: '/api/public/telegram/summary-webhook/$rid'
      fullPath: '/api/public/telegram/summary-webhook/$rid'
      preLoaderRoute: typeof ApiPublicTelegramSummaryWebhookRidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardMenuRoute: typeof DashboardMenuRoute
  DashboardOrdersRoute: typeof DashboardOrdersRoute
  DashboardReviewsRoute: typeof DashboardReviewsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTablesRoute: typeof DashboardTablesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardMenuRoute: DashboardMenuRoute,
  DashboardOrdersRoute: DashboardOrdersRoute,
  DashboardReviewsRoute: DashboardReviewsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTablesRoute: DashboardTablesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface OpsRouteChildren {
  OpsComplaintsRoute: typeof OpsComplaintsRoute
  OpsCustomersRoute: typeof OpsCustomersRoute
  OpsEmployeesRoute: typeof OpsEmployeesRoute
  OpsExpensesRoute: typeof OpsExpensesRoute
  OpsInventoryRoute: typeof OpsInventoryRoute
  OpsInventoryCountRoute: typeof OpsInventoryCountRoute
  OpsRecipesRoute: typeof OpsRecipesRoute
  OpsReportsRoute: typeof OpsReportsRoute
  OpsStaffPerformanceRoute: typeof OpsStaffPerformanceRoute
  OpsSuppliersRoute: typeof OpsSuppliersRoute
  OpsWasteRoute: typeof OpsWasteRoute
  OpsIndexRoute: typeof OpsIndexRoute
}

const OpsRouteChildren: OpsRouteChildren = {
  OpsComplaintsRoute: OpsComplaintsRoute,
  OpsCustomersRoute: OpsCustomersRoute,
  OpsEmployeesRoute: OpsEmployeesRoute,
  OpsExpensesRoute: OpsExpensesRoute,
  OpsInventoryRoute: OpsInventoryRoute,
  OpsInventoryCountRoute: OpsInventoryCountRoute,
  OpsRecipesRoute: OpsRecipesRoute,
  OpsReportsRoute: OpsReportsRoute,
  OpsStaffPerformanceRoute: OpsStaffPerformanceRoute,
  OpsSuppliersRoute: OpsSuppliersRoute,
  OpsWasteRoute: OpsWasteRoute,
  OpsIndexRoute: OpsIndexRoute,
}

const OpsRouteWithChildren = OpsRoute._addFileChildren(OpsRouteChildren)

interface ApiPublicTelegramWebhookRouteChildren {
  ApiPublicTelegramWebhookRidRoute: typeof ApiPublicTelegramWebhookRidRoute
}

const ApiPublicTelegramWebhookRouteChildren: ApiPublicTelegramWebhookRouteChildren =
  {
    ApiPublicTelegramWebhookRidRoute: ApiPublicTelegramWebhookRidRoute,
  }

const ApiPublicTelegramWebhookRouteWithChildren =
  ApiPublicTelegramWebhookRoute._addFileChildren(
    ApiPublicTelegramWebhookRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CashierRoute: CashierRoute,
  CashierLoginRoute: CashierLoginRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  KitchenLoginRoute: KitchenLoginRoute,
  KitchenScreenRoute: KitchenScreenRoute,
  LoginRoute: LoginRoute,
  OpsRoute: OpsRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SetupRoute: SetupRoute,
  SignupRoute: SignupRoute,
  WaiterLoginRoute: WaiterLoginRoute,
  WaiterScreenRoute: WaiterScreenRoute,
  DDelivery_tokenRoute: DDelivery_tokenRoute,
  RQr_tokenRoute: RQr_tokenRoute,
  TTakeaway_tokenRoute: TTakeaway_tokenRoute,
  ApiPublicHooksDailySummaryRoute: ApiPublicHooksDailySummaryRoute,
  ApiPublicHooksDeliveryFollowupRoute: ApiPublicHooksDeliveryFollowupRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRouteWithChildren,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  ApiPublicTelegramSummaryWebhookRidRoute:
    ApiPublicTelegramSummaryWebhookRidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
